linters:
  enable:
    - dogsled
    - errcheck
    - gofmt
    - goimports
    - golint
    - govet
    - lll
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - whitespace
    - goconst
    - gocyclo
    - gosec
    - unused


issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    # Exclude staticcheck messages for deprecated function, variable or constant
    # This causes issues with package github.com/golang/protobuf/proto
    - linters:
        - staticcheck
      text: "SA1019:"